import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { Providers } from './providers';
import "./globals.css";

const quick = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400'],
  style: 'normal'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-light ${quick.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
